//LOGIN
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

//BILLING
export const POST_BILLING = "POST_BILLING";
export const FETCH_BILLING = "FETCH_BILLING";
export const FETCH_BILLINGORDER = "FETCH_BILLINGORDER";
export const FETCH_BILLINGID = "FETCH_BILLINGID";
export const EDIT_BILLING = "EDIT_BILLING";
export const DELETE_BILLING = "DELETE_BILLING";
export const BILLING_LOADING = "BILLING_LOADING";
export const BILLING_FAILED = "BILLING_FAILED";

//ORDER
export const POST_ORDER = "POST_ORDER";
export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDERID = "FETCH_ORDERID";
export const EDIT_ORDER = "EDIT_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const ORDER_LOADING = "ORDER_LOADING";
export const ORDER_FAILED = "ORDER_FAILED";

//CATEGORY
export const POST_CATEGORY = "POST_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORYID = "FETCH_CATEGORYID";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_FAILED = "CATEGORY_FAILED";

//REVERSIBLE
export const POST_REVERSIBLE = "POST_REVERSIBLE";
export const FETCH_REVERSIBLE = "FETCH_REVERSIBLE";
export const FETCH_REVERSIBLEID = "FETCH_REVERSIBLEID";
export const EDIT_REVERSIBLE = "EDIT_REVERSIBLE";
export const DELETE_REVERSIBLE = "DELETE_REVERSIBLE";
export const REVERSIBLE_LOADING = "REVERSIBLE_LOADING";
export const REVERSIBLE_FAILED = "REVERSIBLE_FAILED";

//CLIENT
export const POST_CLIENT = "POST_CLIENT";
export const FETCH_CLIENT = "FETCH_CLIENT";
export const FETCH_CLIENTID = "FETCH_CLIENTID";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const CLIENT_LOADING = "CLIENT_LOADING";
export const CLIENT_FAILED = "CLIENT_FAILED";

//PRODUCT
export const POST_PRODUCT = "POST_PRODUCT";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCTORDER = "FETCH_PRODUCTORDER";
export const FETCH_PRODUCTID = "FETCH_PRODUCTID";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_FAILED = "PRODUCT_FAILED";

//SHIPINVENTORY
export const POST_SHIPINVENTORY = "POST_SHIPINVENTORY";
export const FETCH_SHIPINVENTORY = "FETCH_SHIPINVENTORY";
export const FETCH_SHIPINVENTORYORDER = "FETCH_SHIPINVENTORYORDER";
export const FETCH_SHIPINVENTORYPRODUCT = "FETCH_SHIPINVENTORYPRODUCT";
export const FETCH_SHIPINVENTORYID = "FETCH_SHIPINVENTORYID";
export const EDIT_SHIPINVENTORY = "EDIT_SHIPINVENTORY";
export const DELETE_SHIPINVENTORY = "DELETE_SHIPINVENTORY";
export const SHIPINVENTORY_LOADING = "SHIPINVENTORY_LOADING";
export const SHIPINVENTORY_FAILED = "SHIPINVENTORY_FAILED";

//SHIPMENT
export const POST_SHIPMENT = "POST_SHIPMENT";
export const FETCH_SHIPMENT = "FETCH_SHIPMENT";
export const FETCH_SHIPMENTORDER = "FETCH_SHIPMENTORDER";
export const FETCH_SHIPMENTPRODUCT = "FETCH_SHIPMENTPRODUCT";
export const FETCH_SHIPMENTID = "FETCH_SHIPMENTID";
export const EDIT_SHIPMENT = "EDIT_SHIPMENT";
export const DELETE_SHIPMENT = "DELETE_SHIPMENT";
export const SHIPMENT_LOADING = "SHIPMENT_LOADING";
export const SHIPMENT_FAILED = "SHIPMENT_FAILED";

//DELIVERY
export const POST_DELIVERY = "POST_DELIVERY";
export const FETCH_DELIVERY = "FETCH_DELIVERY";
export const FETCH_DELIVERYORDER = "FETCH_DELIVERYORDER";
export const FETCH_DELIVERYPRODUCT = "FETCH_DELIVERYPRODUCT";
export const FETCH_DELIVERYID = "FETCH_DELIVERYID";
export const EDIT_DELIVERY = "EDIT_DELIVERY";
export const DELETE_DELIVERY = "DELETE_DELIVERY";
export const DELIVERY_LOADING = "DELIVERY_LOADING";
export const DELIVERY_FAILED = "DELIVERY_FAILED";

//STOCK
export const POST_STOCK = "POST_STOCK";
export const FETCH_STOCK = "FETCH_STOCK";
export const FETCH_COUNT = "FETCH_COUNT";
export const FETCH_STOCKID = "FETCH_STOCKID";
export const EDIT_STOCK = "EDIT_STOCK";
export const DELETE_STOCK = "DELETE_STOCK";
export const STOCK_LOADING = "STOCK_LOADING";
export const STOCK_FAILED = "STOCK_FAILED";

//SUPPLIER
export const POST_SUPPLIER = "POST_SUPPLIER";
export const FETCH_SUPPLIER = "FETCH_SUPPLIER";
export const FETCH_SUPPLIERID = "FETCH_SUPPLIERID";
export const EDIT_SUPPLIER = "EDIT_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const SUPPLIER_LOADING = "SUPPLIER_LOADING";
export const SUPPLIER_FAILED = "SUPPLIER_FAILED";

//REPORT
export const POST_REPORT = "POST_REPORT";
export const FETCH_REPORT = "FETCH_REPORT";
export const FETCH_PURCHASEREPORT = "FETCH_PURCHASEREPORT";
export const FETCH_REPORTID = "FETCH_REPORTID";
export const EDIT_REPORT = "EDIT_REPORT";
export const DELETE_REPORT = "DELETE_REPORT";
export const REPORT_LOADING = "REPORT_LOADING";
export const REPORT_FAILED = "REPORT_FAILED";

//USER
export const POST_USER = "POST_USER";
export const FETCH_USER = "FETCH_USER";
export const FETCH_DELIVERYUSER = "FETCH_DELIVERYUSER";
export const FETCH_USERID = "FETCH_USERID";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";
export const USER_LOADING = "USER_LOADING";
export const USER_FAILED = "USER_FAILED";

//WAREHOUSE
export const POST_WAREHOUSE = "POST_WAREHOUSE";
export const FETCH_WAREHOUSE = "FETCH_WAREHOUSE";
export const FETCH_WAREHOUSEID = "FETCH_WAREHOUSEID";
export const EDIT_WAREHOUSE = "EDIT_WAREHOUSE";
export const DELETE_WAREHOUSE = "DELETE_WAREHOUSE";
export const WAREHOUSE_LOADING = "WAREHOUSE_LOADING";
export const WAREHOUSE_FAILED = "WAREHOUSE_FAILED";
